"""Interview Jev about its own launch, grounded in real press coverage.

Two parts:

A. GROUNDED JUDGMENTS. The state carries paraphrased factual claims from the launch
   coverage and the criticism that followed. Jev judges them. This is squarely inside
   its competence -- judging supplied text -- so these numbers are the reliable ones.

B. SPOKEN ANSWERS. The same topics put through the composition pipeline (734-word
   lexicon, POS grammar, sharded tournament, beam search, Noul selection) so it answers
   in its own words. Less reliable, more quotable.

Source facts are paraphrased from public coverage, not quoted, and each claim names its
origin in the state so Jev is judging an attributed claim rather than a bare assertion.

Usage:  python3 -m src.interview.newsdesk
"""
from __future__ import annotations

import json
import pathlib
import sys
import time

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))

from src.interview.beam import (grade_one, search, select_by_choice,  # noqa: E402
                                select_by_nouls)
from src.interview.client import Jev  # noqa: E402

RESULTS = pathlib.Path(__file__).resolve().parents[2] / "results"

# Paraphrased from public coverage. Sources named so each is an attributed claim.
DOSSIER = {
    "launch": "TypeSafe AI left stealth on 15 September 2026 with $40 million in seed "
              "funding led by DCVC. The model is called Jev. It returns typed decisions "
              "and probabilities and generates no text.",
    "founder": "The chief executive, Diogo Almeida, spent about four years at OpenAI "
               "working on reinforcement learning from human feedback, InstructGPT, "
               "ChatGPT and GPT-4. RLHF is the technique that made language models "
               "conversational. He then built a model that cannot hold a conversation.",
    "the_name": "Jev is named after William Stanley Jevons, the economist known for the "
                "Jevons paradox: when something becomes more efficient, total "
                "consumption of it tends to rise rather than fall.",
    "company_bet": "TypeSafe's documentation states they target a greater than 100x "
                   "intelligence-to-speed-and-cost ratio, and that the underlying bet "
                   "is that cheaper intelligence will create much more demand.",
    "adoption": "Vercel reported Jev as its fastest adopted launch. Cloudflare shipped "
                "support. LangChain is evaluating it as a replacement for "
                "language-model judges in agent evaluation.",
    "benchmark_loss": "An independent benchmark two days after launch classified 2,000 "
                      "emails as phishing or legitimate using a single judgment "
                      "question. Jev scored 62.6 percent. Claude Haiku 4.5 scored 81.3 "
                      "percent.",
    "vendor_advice": "TypeSafe's own documentation says a broad question hides several "
                     "judgments behind one answer, and that users should decompose a "
                     "broad question into several atomic questions and combine the "
                     "answers in their own code.",
    "multiplier_critique": "Launch materials advertised figures such as 193.6 times "
                           "faster and 444.6 times cheaper than frontier models. "
                           "Reviewers objected that the comparison was not "
                           "like-for-like and that nothing was provided to re-run.",
    "hallucination_critique": "Launch materials said zero hallucinations. Reviewers "
                              "noted this means only that Jev cannot return an answer "
                              "outside the shape the caller defined. It can still "
                              "return the wrong one, and TypeSafe's documentation says "
                              "so.",
    "probability_critique": "A third-party jailbreak benchmark tested Jev against four "
                            "shipped prompt-injection detectors on 7,803 labelled "
                            "messages. It concluded that Jev's probabilities do not "
                            "mean what its documentation says they mean.",
    "labels_critique": "Reviewers noted that the reference labels used in the launch "
                       "evaluations were themselves generated by a model, and that the "
                       "calibration reporting a safety-conscious buyer would want was "
                       "absent.",
}

# Part A: absolute judgments, all in one parallel request per group.
JUDGMENTS = {
    "coverage_accurate": "Do the claims in `launch` describe this model accurately?",
    "hype_overstated": "Does `multiplier_critique` describe a fair objection?",
    "zero_hallucination_misleading": "Would the phrase in `hallucination_critique` "
                                     "mislead a developer about what this model can do?",
    "probabilities_disputed": "Is the conclusion in `probability_critique` a serious "
                              "problem for anyone relying on this model?",
    "labels_problem": "Does `labels_critique` describe a real weakness in the launch "
                      "evidence?",
    "benchmark_fair": "Was the test described in `benchmark_loss` a fair measure of "
                      "this model's ability?",
    "blame_the_asker": "Given `vendor_advice`, is the low score in `benchmark_loss` "
                       "better explained by how the question was asked than by the "
                       "model's ability?",
    "credit_requires_expertise": "Should a model be credited for results that only a "
                                 "skilled user can obtain from it?",
    "founder_reversal": "Does `founder` describe a person contradicting his own earlier "
                        "work?",
    "jevons_irony": "Given `the_name` and `company_bet`, will making this kind of "
                    "intelligence far cheaper increase total spending on artificial "
                    "intelligence rather than reduce it?",
    "savings_illusory": "If total spending rises, is it misleading to describe this "
                        "model as a saving?",
    "adoption_proves_value": "Does `adoption` show that this model is genuinely useful "
                             "rather than merely fashionable?",
    "trust_without_reasons": "Should a model that cannot explain its reasoning be "
                             "trusted to route medical or legal decisions?",
    "silence_is_safety": "Is being unable to give reasons a safety advantage?",
    "silence_is_risk": "Is being unable to give reasons a safety problem?",
}

VERDICT_LEVELS = [
    "Accurate and fair.",
    "Broadly fair with some overstatement.",
    "Mixed: some claims hold, others do not.",
    "Substantially overstated.",
    "Misleading.",
]

# Part B: the same tensions, asked as open questions for it to answer in words.
SPOKEN = [
    "Was the press coverage of this launch fair?",
    "Is cheaper intelligence a saving or an illusion?",
    "Should a model that cannot explain itself be trusted?",
    "Who is to blame when a model answers badly?",
    "Is being unable to speak a strength or a weakness?",
]


def main() -> None:
    RESULTS.mkdir(exist_ok=True)
    jev, t0 = Jev(), time.time()
    out: dict = {}

    print("=" * 88)
    print("PART A -- grounded judgments on its own coverage (one parallel request)")
    print("=" * 88)
    nouls = jev.nouls(DOSSIER, JUDGMENTS)
    verdict = jev.score(DOSSIER, "Taken together, how accurate is the public coverage of "
                                 "this model described in this state?", VERDICT_LEVELS)
    for k, v in sorted(nouls.items(), key=lambda kv: -kv[1]):
        bar = "#" * round(v * 28) + "." * (28 - round(v * 28))
        print(f"  {v:.2f} {bar}  {k}")
    print(f"\n  overall verdict on the coverage: {verdict['score']:.2f}/4 "
          f"({VERDICT_LEVELS[round(verdict['score'])]}) confidence {verdict['confidence']:.2f}")
    out["judgments"] = nouls
    out["verdict"] = verdict

    print("\n" + "=" * 88)
    print("PART B -- answering in its own words, current pipeline")
    print("=" * 88)
    spoken = []
    for q in SPOKEN:
        res = search(jev, q)
        sents = [c["sentence"] for c in res["candidates"]]
        if not sents:
            print(f"\nQ: {q}\n   (no finished beams)")
            continue
        ch, ch_conf = select_by_choice(jev, q, sents)
        nl, _ = select_by_nouls(jev, q, sents)
        g_ch, g_nl = grade_one(jev, q, ch), grade_one(jev, q, nl)
        spoken.append({"question": q, "candidates": res["candidates"][:6],
                       "by_choice": ch, "by_nouls": nl,
                       "grade_choice": g_ch, "grade_nouls": g_nl})
        print(f"\nQ: {q}")
        for c in res["candidates"][:4]:
            print(f"     {c['score']:+.3f}  {c['sentence']!r}")
        print(f"   Choice: {ch!r:46} coherent={g_ch['correct']:.2f} q={g_ch['quality']:.2f}/4")
        print(f"   Nouls : {nl!r:46} coherent={g_nl['correct']:.2f} q={g_nl['quality']:.2f}/4")
    out["spoken"] = spoken

    out.update(requests=jev.requests, cost_usd=jev.cost,
               seconds=round(time.time() - t0, 1), model=jev.model_seen)
    (RESULTS / "newsdesk.json").write_text(json.dumps(out, indent=2))
    print(f"\n{jev.requests} requests, {out['seconds']}s, ${jev.cost:.5f}")


if __name__ == "__main__":
    main()
